Repository HackYourFuture-CPH/fp-class12, pull requests merged in 2020-06, with the labels that each got.

#68 Game_instances and Actual_answers #42
  src/server/migrations/20200602233442_create_game_instances_table.js
  src/server/migrations/20200602233519_create_actual_answers_table.js
Labels: databases

#66 Created Users, Roles and User_Roles tables with knex in the database
  src/server/migrations/20200602194903_users.js
  src/server/migrations/20200602213830_roles.js
  src/server/migrations/20200603001057_user_roles.js
Labels: databases

#58 Knex-Questions, Answer_choices, Game_factory, Themes and Maps
  src/server/migrations/20200602211147_themes.js
  src/server/migrations/20200602212442_maps.js
  src/server/migrations/20200602213728_game_factory.js
  src/server/migrations/20200602214116_questions.js
  src/server/migrations/20200602225007_answer_choices.js
Labels: databases

#91 Add FK to the game_instances and actual_answers
  src/server/migrations/20200608220409_game_instances.js
  src/server/migrations/20200608220954_actual_answers.js
Labels: databases

#124 marker and circle marker current location
  src/client/components/CircleAndMarkerCurrentLocation/Icons.js
  src/client/components/CircleAndMarkerCurrentLocation/MarkerCurrentLocation.js
  src/client/components/CircleAndMarkerCurrentLocation/MarkerCurrentLocation.stories.js
Labels: storybook

#128 creating avatars table
  src/server/migrations/20200616135151_avatars.js
  src/server/migrations/20200617125636_add_fk_avatar_id.js
Labels: databases

#139 added fk to game_scores table
  src/server/migrations/20200617203514_game_scores.js
Labels: databases

#130 Sorted stories alphabetically
  src/client/.storybook/config.js
Labels: storybook

#143 Updating Project's name
  public/index.html
Labels: frontend

#93 Added endpoint to retrieve the coordinates of a checkpoint question
  src/server/api/controllers/questions.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/questions.router.js
  src/server/api/routes/router.js
Labels: backend

#119 Modifications in Tables
  src/server/migrations/20200602194903_users.js
  src/server/migrations/20200602213728_game_factory.js
  src/server/migrations/20200602213830_roles.js
  src/server/migrations/20200602214116_questions.js
  src/server/migrations/20200602225007_answer_choices.js
  src/server/migrations/20200603001057_user_roles.js
  src/server/migrations/20200608220409_game_instances.js
  src/server/migrations/20200608220954_actual_answers.js
Labels: databases

#131 Endpoint to List the Questions of a game
  src/server/api/controllers/questions.controller.js
  src/server/api/routes/questions.router.js
Labels: backend

#140 Start Game Page frontend page
  __mocks__/fileMock.js
  src/client/App.css
  src/client/containers/Home/Home.js
Labels: frontend

#97 Creating user and its associated roles and avatar between users and user_roles table
  src/server/api/controllers/create-user-profiles.controller.js
  src/server/api/controllers/create-user-roles.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/create-user-profiles.routes.js
  src/server/api/routes/create-user-roles.routes.js
  src/server/api/routes/router.js
Labels: backend

#145 add new field game_timer
  src/server/api/routes/api-router.js
  src/server/api/routes/router.js
  src/server/migrations/20200619230308_game_timer_field.js
Labels: databases

#125 Endpoint for possible Answers of a specific Question
  src/server/api/controllers/GameQuestionAnswerOptions.controller.js
  src/server/api/routes/GameQuestionAnswerOptions.router.js
  src/server/api/routes/api-router.js
  src/server/api/routes/router.js
Labels: backend

#96 Feature/seeds
  src/server/seeds/development/01_roles.js
  src/server/seeds/development/02_themes.js
  src/server/seeds/development/03_maps.js
  src/server/seeds/development/04_avatars.js
  src/server/seeds/development/05_users.js
  src/server/seeds/development/06_user_roles.js
  src/server/seeds/development/07_game_factory.js
  src/server/seeds/development/08_questions.js
  src/server/seeds/development/09_answer_choices.js
Labels: databases

#150 Added FKs and Finished in Game_instances
  src/server/migrations/20200621132151_add_fks_game_instances.js
  src/server/migrations/20200621133302_add_finished_field.js
  src/server/migrations/20200621134036_add_fk_user_id.js
  src/server/migrations/20200621134207_add_fk_game_id.js
Labels: databases

#167 Modifications in the game_instances table
  src/server/migrations/20200623182139_remove_score_in_game_instances.js
  src/server/migrations/20200623223721_rename_to_game_code.js
Labels: databases

#104 Feature/game instances endpoint
  src/server/api/controllers/gameInstances.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/gameInstances.router.js
  src/server/api/routes/router.js
Labels: backend

#148 Endpoint all users played a game-Leaderboard
  src/server/api/controllers/getAllUsers.controller.js
  src/server/api/routes/allUsers.router.js
  src/server/api/routes/api-router.js
  src/server/api/routes/router.js
Labels: backend

#122 Endpoint to retrieve coordinates of map
  src/server/api/controllers/coordinates.controller.js
  src/server/api/controllers/mapcoordinates.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/coordinates.router.js
  src/server/api/routes/mapcoordinates.router.js
  src/server/api/routes/router.js
Labels: backend

#169 Adding a new component in to modal named as Content modal.
  src/client/components/Modal/ContentModal.js
  src/client/components/Modal/ContentModal.stories.js
  src/client/components/Modal/ContentModalPopup.js
  src/client/components/Modal/ListModal.js
  src/client/components/Modal/ListModal.stories.js
  src/client/components/Modal/ListModalContent.js
  src/client/components/Modal/ListModalPopup.js
  src/client/components/Modal/Modal.styles.css
Labels: frontend

#155 Get all question for a particular game instance based on game factory/game instance id
  src/server/api/controllers/questions.controller.js
  src/server/api/routes/questions.router.js
  src/server/migrations/20200602214116_questions.js
  src/server/migrations/20200608220409_game_instances.js
  src/server/migrations/20200621133302_add_finished_field.js
  src/server/migrations/20200622165517_rename_cols_game_instances.js
  src/server/migrations/20200622165958_rename_col_questions.js
  src/server/migrations/20200623223721_rename_to_game_code.js
Labels: backend

#174 Get a specific question with question Id for a particular game instance
  src/server/api/controllers/getQuestionById.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/getQuestionById.router.js
  src/server/api/routes/router.js
Labels: backend

#146 New game instance
  src/server/api/controllers/create-new-game-instance.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/create-new-game.router.js
  src/server/api/routes/router.js
Labels: backend

#171 Add Avatar Component
  src/client/components/AddAvatarComponent/AddAvatarComponent.js
  src/client/components/AddAvatarComponent/AddAvatarComponent.stories.js
  src/client/components/AddAvatarComponent/AddAvatarComponent.styles.css
Labels: storybook

#170 Endpoind retrive next question when answered correct
  src/server/api/controllers/next-questions.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/next-questions.router.js
  src/server/api/routes/router.js
Labels: backend
